# Generated by Django 5.2 on 2025-04-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header",
                    models.CharField(help_text="Введите заголовок", max_length=100),
                ),
                ("description", models.TextField(verbose_name="Описание продукта")),
                (
                    "preview",
                    models.ImageField(
                        help_text="Загрузите изображение", upload_to="blog/photo/"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_publication",
                    models.BooleanField(verbose_name="Cтатус публикации"),
                ),
                (
                    "views_count",
                    models.IntegerField(verbose_name="Количество просмотров"),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Мой личный блог",
                "ordering": ["created_at", "views_count"],
            },
        ),
    ]
