# Generated by Django 5.2 on 2025-05-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="description",
            field=models.TextField(verbose_name="Текст статьи"),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="header",
            field=models.CharField(
                help_text="Введите заголовок", max_length=100, verbose_name="Заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="blog/photo/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
