# Generated by Django 5.2 on 2025-09-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_image_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "price"],
                "permissions": [
                    ("can_unpublish_product", "Can Unpublish Product"),
                    ("can_remove_product", "Can Remove Product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_publication",
            field=models.BooleanField(default=False),
        ),
    ]
